language: python
python:
  - "3.6"
# command to install dependencies
install:
 - "pip install -r requirements.txt"
 - "pip install python-coveralls"
 - "pip install nose"
# command to run tests
script:

 
 - coveralls
 - python -m nose --with-coverage
after-success: coveralls
