language: python
python:
  - "3.6.2"
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - DB=sqlite
# command to run tests
script: nosetests --with-coverage

after_success:
  - coveralls
